# Generated by Django 3.2.23 on 2024-02-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichkham',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
