# Generated by Django 3.2.23 on 2024-02-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_lichkham_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='NgaySinh',
        ),
    ]
