# Generated by Django 3.2.23 on 2024-02-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_remove_user_ngaysinh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toathuoc',
            name='ChuThich',
        ),
        migrations.RemoveField(
            model_name='toathuoc',
            name='CongDuong',
        ),
        migrations.RemoveField(
            model_name='toathuoc',
            name='LieuLuong',
        ),
        migrations.RemoveField(
            model_name='toathuoc',
            name='MaThuoc',
        ),
        migrations.RemoveField(
            model_name='toathuoc',
            name='SoLuong',
        ),
        migrations.CreateModel(
            name='ChiTietToaThuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CongDuong', models.TextField()),
                ('SoLuong', models.IntegerField()),
                ('LieuLuong', models.CharField(max_length=50)),
                ('ChuThich', models.TextField(blank=True)),
                ('Thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.thuoc')),
                ('ToaThuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.toathuoc')),
            ],
        ),
        migrations.AddField(
            model_name='toathuoc',
            name='Thuoc',
            field=models.ManyToManyField(related_name='ToaThuoc', through='Web.ChiTietToaThuoc', to='Web.Thuoc'),
        ),
    ]
