# Generated by Django 3.2.23 on 2024-02-13 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_auto_20240213_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhan',
            name='MaTT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BenhAn_TT', to='Web.toathuoc'),
        ),
        migrations.AlterField(
            model_name='benhan',
            name='NgayKham',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='benhan',
            name='NoiDung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
